#!/bin/bash
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function value_for() {
  local -r var="$1"
  local -r line="$(grep -wh "^${var}" bazel-out/{volatile,stable}-status.txt)"
  printf "%s\n" "${line//${var} }"
}

VERSION="$(value_for STABLE_VERSION)"
readonly VERSION

cat <<EOF
#include "absl/strings/string_view.h"
#include "services/common/util/build_info.h"

namespace privacy_sandbox::bidding_auction_servers {

constexpr std::string_view kBuildVersion = "${VERSION}";

}  // namespace privacy_sandbox::bidding_auction_servers
EOF
