#!/usr/bin/env bash

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file sets default values for various environment variables used
# by one or more start_* scripts. Override the default by setting the
# corresponding environment variable before running the start_* script.
BIDDING_PORT="${BIDDING_PORT:-50057}"
AUCTION_PORT="${AUCTION_PORT:-50061}"
BFE_PORT="${BFE_PORT:-50051}"
SFE_PORT="${SFE_PORT:-50053}"
SKIP_TLS_VERIFICATION="${SKIP_TLS_VERIFICATION:-false}"
BUYER_REPORT_WIN_URL="${BUYER_REPORT_WIN_URL:-}"
BUYER_REPORT_WIN_SCRIPT="${BUYER_REPORT_WIN_SCRIPT:-}"
BUYER_PAS_REPORT_WIN_SCRIPT="${BUYER_PAS_REPORT_WIN_SCRIPT:-}"
AUCTION_JS_URL="${AUCTION_JS_URL:-}"
PS_VERBOSITY="${PS_VERBOSITY:-10}"
ENABLE_KANON="${ENABLE_KANON:-false}"
ENABLE_PROTECTED_AUDIENCE="${ENABLE_PROTECTED_AUDIENCE:-true}"
ENABLE_PROTECTED_APP_SIGNALS="${ENABLE_PROTECTED_APP_SIGNALS:-false}"
TELEMETRY_CONFIG="${TELEMETRY_CONFIG:-mode: EXPERIMENT metric_export_interval_ms: 600000}"

# Pass in custom docker arguments as a string such as:
# DOCKER_RUN_ARGS_STRING="--network host -p 172.16.117.19:80:50051"
if [[ -z "$DOCKER_RUN_ARGS_STRING" ]]; then
    DOCKER_RUN_ARGS=(
        "--network=host"
        "--security-opt=seccomp=unconfined"
        "--security-opt=apparmor=unconfined"
    )
else
    # Convert DOCKER_RUN_ARGS_STRING to an array DOCKER_RUN_ARGS
    read -r -a DOCKER_RUN_ARGS <<< "${DOCKER_RUN_ARGS_STRING}"
fi

SELLER_CODE_FETCH_CONFIG=$(cat << END
--seller_code_fetch_config={
      "fetchMode": 0,
      "auctionJsPath": \"\",
      "auctionJsUrl": \"${AUCTION_JS_URL}\",
      "urlFetchPeriodMs": 13000000,
      "urlFetchTimeoutMs": 30000,
      "enableSellerDebugUrlGeneration": true,
      "enableReportResultUrlGeneration": true,
      "enableReportWinUrlGeneration": true,
      "enablePrivateAggregateReporting": false,
      "buyerReportWinJsUrls": {\"${BUYER_REPORT_WIN_URL}\":\"${BUYER_REPORT_WIN_SCRIPT}\"},
      "protectedAppSignalsBuyerReportWinJsUrls": {\"${BUYER_REPORT_WIN_URL}\":\"${BUYER_PAS_REPORT_WIN_SCRIPT}\"}
    }
END
)
