#!/usr/bin/env bash

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source $(dirname "$0")/common
export PROJECT_ROOT=$(git rev-parse --show-toplevel)
declare -a -r DOCKER_RUN_ARGS=(
  "--volume=${PROJECT_ROOT}/bazel-bin/services/seller_frontend_service/server:/server"
  "--name=sfe"
)
export EXTRA_DOCKER_RUN_ARGS="${COMMON_DOCKER_RUN_ARGS[@]} ${DOCKER_RUN_ARGS[@]}"


export SERVER_START_CMD=$(cat << END
/server \
--init_config_client="false" --port=50053 \
--auction_server_host="127.0.0.1:50061" \
--key_value_signals_host="https://pubads.g.doubleclick.net/td/sts" \
--seller_origin_domain="https://securepubads.g.doubleclick.net" \
--seller_cloud_platforms_map='{"component-seller1.com":"GCP", "component-seller2.com":"AWS"}' \
--buyer_server_hosts='{
  "https://td.doubleclick.net": {
    "url": "127.0.0.1:50051",
    "cloudPlatform": "LOCAL"
  }
}' \
--enable_seller_frontend_benchmarking="true" \
--score_ads_rpc_timeout_ms=60000 \
--get_bid_rpc_timeout_ms=60000 --key_value_signals_fetch_rpc_timeout_ms 60000 \
--create_new_event_engine="false" \
--test_mode="true" \
--telemetry_config="mode: EXPERIMENT" \
--enable_otel_based_logging="false" \
--consented_debug_token="" \
--ps_verbosity=2 \
--enable_protected_audience="true" \
--sfe_tcmalloc_background_release_rate_bytes_per_second=4096 \
--sfe_tcmalloc_max_total_thread_cache_bytes=10737418240 \
--enable_protected_app_signals="false" && exit
END
)

if [[ $1 == "--gdb" ]]; then
  ${PROJECT_ROOT}/builders/tools/cbuild --seccomp-unconfined \
  --docker-network host --image build-debian \
  --cmd "apt-get update && apt-get -y install gdb && gdb -ex=r --args ${SERVER_START_CMD}"
else
  ${PROJECT_ROOT}/builders/tools/cbuild --seccomp-unconfined  --docker-network host --image build-debian --cmd  "${SERVER_START_CMD}"
fi
