#!/usr/bin/env bash
# Copyright 2024 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source $(dirname "$0")/common

SERVICE_NAME=auction
BIN=${SERVICE_NAME}
if [[ -z $1 ]]; then
  # When we load from .tar file, we don't mount the binary
  # and it is embededd as "server"
  BIN="server"
fi

SERVER_START_CMD=$(cat << END
/server/bin/${BIN} \
--https_fetch_skips_tls_verification="${SKIP_TLS_VERIFICATION}" \
--init_config_client="false" \
--port=${AUCTION_PORT} \
--scoring_signals_fetch_mode="${SCORING_SIGNALS_FETCH_MODE}" \
--enable_auction_service_benchmark="true" \
--udf_num_workers=4 \
--js_worker_queue_len=100 \
--test_mode="true" \
--telemetry_config="${TELEMETRY_CONFIG}" \
--roma_timeout_ms="120000" \
--enable_report_win_input_noising="false" \
"${SELLER_CODE_FETCH_CONFIG}" \
--enable_otel_based_logging="true" \
--consented_debug_token="test_token" \
--ps_verbosity=${PS_VERBOSITY} \
--enable_protected_audience=${ENABLE_PROTECTED_AUDIENCE} \
--enable_kanon=${ENABLE_KANON} \
--auction_tcmalloc_background_release_rate_bytes_per_second=4096 \
--auction_tcmalloc_max_total_thread_cache_bytes=10737418240 \
--enable_protected_app_signals=${ENABLE_PROTECTED_APP_SIGNALS} && exit
END
)

PROF_PORT="${PROF_PORT:-1236}"
run_server "$1" "${SERVICE_NAME}" "${SERVER_START_CMD}" ${PROF_PORT}
