#!/usr/bin/env bash

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source $(dirname "$0")/common
export PROJECT_ROOT=$(git rev-parse --show-toplevel)
declare -a -r DOCKER_RUN_ARGS=(
  "--volume=${PROJECT_ROOT}/bazel-bin/services/buyer_frontend_service/server:/server"
  "--name=bfe"
)
export EXTRA_DOCKER_RUN_ARGS="${COMMON_DOCKER_RUN_ARGS[@]} ${DOCKER_RUN_ARGS[@]}"

export SERVER_START_CMD=$(cat << END
/server \
--init_config_client="false" --port=50051 \
--bidding_server_addr="127.0.0.1:50057" \
--buyer_kv_server_addr="https://googleads.g.doubleclick.net/td/bts" \
--enable_buyer_frontend_benchmarking="true" \
--generate_bid_timeout_ms=60000 --bidding_signals_load_timeout_ms 60000 \
--protected_app_signals_generate_bid_timeout_ms=60000 \
--create_new_event_engine="false" \
--test_mode="true" \
--telemetry_config="mode: EXPERIMENT" \
--enable_otel_based_logging="false" \
--consented_debug_token="" \
--ps_verbosity=2 \
--enable_protected_audience="true" \
--bfe_tcmalloc_background_release_rate_bytes_per_second=4096 \
--bfe_tcmalloc_max_total_thread_cache_bytes=10737418240 \
--enable_protected_app_signals="false" && exit
END
)

if [[ $1 == "--gdb" ]]; then
  ${PROJECT_ROOT}/builders/tools/cbuild --seccomp-unconfined \
  --docker-network host --image build-debian \
  --cmd "apt-get update && apt-get -y install gdb && gdb -ex=r --args ${SERVER_START_CMD}"
else
  ${PROJECT_ROOT}/builders/tools/cbuild --seccomp-unconfined  --docker-network host --image build-debian --cmd  "${SERVER_START_CMD}"
fi
