#!/bin/bash
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o pipefail
set -o errexit
export TZ=Etc/UTC
export PS4='+\tZ $(basename ${BASH_SOURCE[0]}):${LINENO} ' # xtrace prompt

START=$(date +%s)

trap _print_runtime EXIT
function _print_runtime() {
  declare -r -i STATUS=$?
  declare -r END=$(date +%s)
  /usr/bin/env LC_ALL=en_US.UTF-8 printf "\nbuild_and_test_all_in_docker runtime: %'ds\n" $((END - START)) >/dev/stderr
  if [[ ${STATUS} -eq 0 ]]; then
    printf "build_and_test_in_docker completed successfully\n" &>/dev/stderr
  else
    printf "Error: build_and_test_in_docker completed with status code: %s\n" "${STATUS}" &>/dev/stderr
    if [[ -v KOKORO_ARTIFACTS_DIR ]]; then
      sleep 5s
    fi
  fi
  exit ${STATUS}
}

declare -a SERVICES
declare INSTANCE
declare -i E2E=0
declare BUILD_FLAVOR=prod
declare PLATFORM
declare -i VERBOSE=0
declare VERBOSE_ARG=
declare -i PRECOMMIT_ONLY=0
declare -i SKIP_PRECOMMIT=0
declare -i NO_TESTS=0
declare -i NO_PLATFORM_BUILD=0
declare -a AMI_REGIONS
declare AWS_IMAGE_TAG
declare GCP_IMAGE_TAG
declare GCP_IMAGE_REPO
declare -i GCP_SKIP_IMAGE_UPLOAD=0
declare -a BUILD_TARGETS=(
  "//tools/secure_invoke/..."
)
declare -a TEST_TARGETS+=(
  "//services/common/..."
  "//tools/secure_invoke/..."
)

function usage() {
  local -i -r exitval=${1-1}
  cat >&2 <<USAGE
usage:
  $0 <options>
    --service-path               [REQUIRED] Recognized values: auction_service, bidding_service, buyer_frontend_service, seller_frontend_service.
                                   Use multiple times to specify more than one service.
    --instance                   [REQUIRED] Recognized values: local, aws
    --platform                   [REQUIRED] Recognized values: gcp, aws
    --e2e                        Run e2e mode
    --build-flavor               Recognized values: prod, non_prod, inference_non_prod. Default: prod
                                   Use non_prod to enable verbose logging.
    --precommit-only             Run precommit then exit
    --no-precommit               Skip precommit checks
    --no-tests                   Skip tests
    --no-platform-build          Skip platform-specific building and testing
    --verbose                    Enable verbose output

If platform is aws:
    --with-ami                   AMI region in which to build and store AWS AMIs.
                                   Use multiple times to specify more than one region.
                                   If empty or not specified, none will be built.
    --aws-image-tag              Custom image tag for AMI image. Applied to AMI as tag value for key 'build_env'.

If platform is gcp:
    --gcp-skip-image-upload       Skip GCP image upload (and sha256 recording).
    --gcp-image-tag              [REQUIRED if no --gcp-skip-image-upload] (All lowercase) Custom image tag for GCP image.
    --gcp-image-repo             [REQUIRED if no --gcp-skip-image-upload] The target repo for TEE image upload. Ex: us-docker.pkg.dev/my-project-id/services

environment variables (all optional):
    WORKSPACE                    Set the path to the workspace (repo root)
    BAZEL_STARTUP_ARGS           Additional startup arguments to pass to bazel invocations
    BAZEL_EXTRA_ARGS             Additional command arguments to pass to bazel invocations
    EXTRA_DOCKER_RUN_ARGS        Additional arguments to pass to docker run invocations
USAGE
  exit ${exitval}
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --precommit-only)
      PRECOMMIT_ONLY=1
      shift
      ;;
    --no-tests)
      NO_TESTS=1
      shift
      ;;
    --e2e)
      E2E=1
      shift
      ;;
    --gcp-skip-image-upload)
      GCP_SKIP_IMAGE_UPLOAD=1
      shift
      ;;
    --no-platform-build)
      NO_PLATFORM_BUILD=1
      shift
      ;;
    --no-precommit)
      SKIP_PRECOMMIT=1
      shift
      ;;
    --with-ami)
      AMI_REGIONS+=("$2")
      shift 2 || usage
      ;;
    --aws-image-tag)
      AWS_IMAGE_TAG+=("$2")
      shift 2 || usage
      ;;
    --service-path)
      SERVICES+=("$2")
      shift 2 || usage
      ;;
    --instance)
      INSTANCE="$2"
      shift 2 || usage
      ;;
    --build-flavor)
      BUILD_FLAVOR="$2"
      shift 2 || usage
      ;;
    --platform)
      PLATFORM="$2"
      shift 2 || usage
      ;;
    --gcp-image-tag)
      GCP_IMAGE_TAG="$2"
      shift 2 || usage
      ;;
    --gcp-image-repo)
      GCP_IMAGE_REPO="$2"
      shift 2 || usage
      ;;
    --verbose)
      VERBOSE=1
      shift
      ;;
    -h | --help) usage 0 ;;
    *) usage ;;
  esac
done

if [[ ${#SERVICES[@]} -eq 0 ]]; then
  printf "Error: A minimum of one --service-path must be specified\n" &>/dev/stderr
  usage
fi
if [[ -z ${PLATFORM} ]]; then
  printf "Error: --platform must be specified\n" &>/dev/stderr
  usage
fi
if [[ -z ${INSTANCE} ]]; then
  printf "Error: --instance must be specified\n" &>/dev/stderr
  usage
fi
if [[ ${PLATFORM} = gcp ]]; then
  if [[ ${GCP_SKIP_IMAGE_UPLOAD} -eq 0 ]]; then
    if [[ -z ${GCP_IMAGE_TAG} ]]; then
      printf "Error: --gcp-image-tag must be specified\n" &>/dev/stderr
      usage
    fi
    if [[ -z ${GCP_IMAGE_REPO} ]]; then
      printf "Error: --gcp-image-repo must be specified\n" &>/dev/stderr
      usage
    fi
  fi
fi
if [[ -n ${AMI_REGIONS[0]} ]]; then
  if [[ ${PLATFORM} != "aws" ]]; then
    printf "Cannot use AMI regions if platform != aws\n"
    exit 1
  fi
  if [[ ${INSTANCE} != aws ]]; then
    printf "Error: Expecting --instance=aws when AMI region is specified\n"
    exit 1
  fi
fi

BAZEL_EXTRA_ARGS="${BAZEL_EXTRA_ARGS} --config=${INSTANCE}_${PLATFORM} --config=${BUILD_FLAVOR}"
if [[ ${E2E} -eq 1 ]]; then
  BAZEL_EXTRA_ARGS="${BAZEL_EXTRA_ARGS} --//:build_for_test=e2e"
fi
CBUILD_ARGS="${CBUILD_ARGS} --seccomp-unconfined"
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
readonly SCRIPT_DIR

# shellcheck source=builders/tools/builder.sh
source "${SCRIPT_DIR}"/../../builders/tools/builder.sh

if [[ ${VERBOSE} -eq 1 ]]; then
  set -o xtrace
  VERBOSE_ARG="--verbose"
  CBUILD_ARGS="${CBUILD_ARGS} --verbose"
fi

if [[ ${SKIP_PRECOMMIT} -eq 0 ]]; then
  "${WORKSPACE}"/builders/tools/pre-commit
fi
if [[ ${PRECOMMIT_ONLY} -eq 1 ]]; then
  exit 0
fi

for svc in "${SERVICES[@]}"; do
  BUILD_TARGETS+=(
    "//production/packaging/${PLATFORM}/${svc}/..."
  )
  TEST_TARGETS+=(
    "//services/${svc}/..."
    "//production/packaging/${PLATFORM}/${svc}/..."
  )
done

printf "==== build and test specified platform=%s, instance=%s build_flavor=%s targets using bazel-debian for: %s ====\n" "${PLATFORM}" "${INSTANCE}" "${BUILD_FLAVOR}" "${SERVICES[*]}"

function invoke_targets() {
  declare -r build_targets="${BUILD_TARGETS[*]}"
  declare -r test_targets="${TEST_TARGETS[*]}"

  builder::cbuild_debian "
  trap _collect_logs EXIT
  function _collect_logs() {
    local -r -i STATUS=\$?
    printf 'Collecting bazel logs... (status: %d)\n' \${STATUS} &>/dev/stderr
    bazel ${BAZEL_STARTUP_ARGS} run ${BAZEL_EXTRA_ARGS} //:collect-logs
    exit \${STATUS}
  }
  set -o errexit

  if [[ ${NO_TESTS} -eq 0 ]]; then
    bazel ${BAZEL_STARTUP_ARGS} test ${BAZEL_EXTRA_ARGS} --build_tests_only --config=coretests ${test_targets}
  fi
  bazel ${BAZEL_STARTUP_ARGS} build ${BAZEL_EXTRA_ARGS} ${build_targets}
  for svc in ${SERVICES[*]}; do
    bazel ${BAZEL_STARTUP_ARGS} run ${BAZEL_EXTRA_ARGS} //production/packaging/${PLATFORM}/\${svc}:copy_to_dist
  done
  "
}

function build_service_for_aws() {
  declare -r service="$1"
  declare -n extra_args="$2"
  # note: use relative path to dist
  declare -r docker_image=dist/debian/${service}_image.tar
  if ! [[ -s ${WORKSPACE}/${docker_image} ]]; then
    printf "Error: docker image tar file not found: %s\n" "${docker_image}" &>/dev/stderr
    exit 1
  fi
  # shellcheck disable=SC2086
  "${SCRIPT_DIR}"/aws/build_and_test ${VERBOSE_ARG} \
    --server-image "${docker_image}" \
    --service-path "${service}" \
    --build-flavor ${BUILD_FLAVOR} \
    "${extra_args[@]}"
}

function build_service_for_gcp() {
  declare -r service="$1"
  # note: use relative path to dist
  declare -r docker_image=dist/debian/${service}_image.tar
  if ! [[ -s ${WORKSPACE}/${docker_image} ]]; then
    printf "Error: docker image tar file not found: %s\n" "${docker_image}" &>/dev/stderr
    exit 1
  fi
  create_gcp_dist "${docker_image}"
  if [[ ${GCP_SKIP_IMAGE_UPLOAD} -eq 1 ]]; then
    printf "==== Skipping default repo image upload. No image_digest will be recorded.  =====\n"
  else
    upload_image_to_repo \
    "${service}" \
    "${docker_image}" \
    "${GCP_IMAGE_REPO}" \
    "${GCP_IMAGE_TAG}" \
    "${BUILD_FLAVOR}"
  fi
}

function load_service_image() {
  declare -r service="$1"
  declare -r docker_image=dist/debian/${service}_image.tar
  if ! [[ -s ${WORKSPACE}/${docker_image} ]]; then
    printf "Error: docker image tar file not found: %s\n" "${docker_image}" &>/dev/stderr
    exit 1
  fi

  docker load -i ${WORKSPACE}/${docker_image}
}

invoke_targets

if [[ ${NO_PLATFORM_BUILD} -eq 0 ]]; then
  case "${PLATFORM}" in
    aws)
      declare -a EXTRA_ARGS
      for region in "${AMI_REGIONS[@]}"; do
        EXTRA_ARGS+=(--with-ami "${region}")
      done
      if [[ -n "${AWS_IMAGE_TAG}" ]]; then
        EXTRA_ARGS+=(--aws-image-tag ${AWS_IMAGE_TAG})
      fi
      if [[ ${VERBOSE} -eq 1 ]]; then
        EXTRA_ARGS+=("--verbose")
      fi

      for svc in "${SERVICES[@]}"; do
        build_service_for_aws "${svc}" EXTRA_ARGS
      done
      ;;
    gcp)
      source  "${SCRIPT_DIR}"/gcp/lib_gcp_artifacts.sh
      for svc in "${SERVICES[@]}"; do
        build_service_for_gcp "${svc}"
      done
    ;;
    *)
      printf "Unsupported platform: %s\n" "${PLATFORM}" >/dev/stderr
      exit 1
      ;;
  esac
else
  for svc in "${SERVICES[@]}"; do
    load_service_image "${svc}"
  done
fi

declare -r DIST="${WORKSPACE}"/dist
if [[ -d ${DIST} ]]; then
  printf "build artifacts:\n"
  ls -lhR "${DIST}"
else
  printf "dir not found: [%s]\n" "${DIST}"
fi
