load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "9c6e26911a79fbf510a8f06d8eedb40f412023cf7fa6d1461def27116bff022c",
    strip_prefix = "rules_python-1.1.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/1.1.0/rules_python-1.1.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

### Initialize Python headers

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "cost_estimation_deps",
    requirements_lock = "//:requirements_lock.txt",
)

load("@cost_estimation_deps//:requirements.bzl", cost_estimation_install_deps = "install_deps")

cost_estimation_install_deps()
